repo:
  - '*'

CMakeLists:
  - 'TetrisSFML/CMakeLists.txt'

readme:
  - 'README.md'

github-actions:
  - '.github/**/*.yml'

src:
  - 'TetrisSFML/**/*.{cpp,hpp}'

main:
  - 'TetrisSFML/main.*'

tetrominos:
  - 'TetrisSFML/'
  - 'TetrisSFML/Tetromino.*'

SFML:
  - 'TetrisSFML/include/SFML/**'
