repo:
  - '*'

CMakeLists:
  - 'TetrisSFML/CMakeLists.txt'

readme:
  - 'README.md'

github-actions:
  - '.github/**/*.yml'

src:
  - 'TetrisSFML'

main:
  - 'TetrisSFML/main.*'

tetrominos:
  - 'TetrisSFML/Tetrominos/**'
  - 'TetrisSFML/Tetrominos.*'

SFML:
  - 'TetrisSFML/include/SFML/**'
