repo:
  - '*'

CMakeLists:
  - 'TetrisSFML/CMakeLists.txt'

readme:
  - 'README.md'

github-actions:
  - '.github/**/*.yml'

src:
  - 'TetrisSFML/**/*.{cpp,h}'

main:
  - 'TetrisSFML/main.*'

Tetris:
  - 'TetrisSFML/Tetris.{cpp,h}'

tetrominos:
  - 'TetrisSFML/Tetromino.{cpp,h}'

SFML:
  - 'TetrisSFML/include/SFML/**'
